services:
  frontend:
    build: ./frontend
    ports:
      - "8080:80"
    secrets:
      - pg-credentials
    networks: 
      - front-network
      - back-network
    environment:
      - DB_USER
      - DB_PASS
      - DB_HOST
      - DB_PORT
      - DB
      - BACKEND_PORT
      - BACKEND_HOST
    depends_on:
      - pgdb
      - backend

  backend:
    build: ./backend
    ports:
      - "${BACKEND_PORT:-7000}:8000"
    networks:
      - back-network
    secrets:
      - pg-credentials
    environment:
      - DB_USER
      - DB_PASS
      - DB_HOST
      - DB_PORT
      - DB
    depends_on:
      - pgdb


  pgdb:
    image: postgres
    networks:
      - back-network
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=${DB:-sest}
      - POSTGRES_USER=${DB_USER:-postgres}
      - POSTGRES_PASSWORD=${DB_PASS:-password}


secrets:
  pg-credentials:
    file: .env


networks:
  front-network: {}
  
  back-network: {}