services:
  frontend:
    build: ./frontend
    ports:
      - "8000:80"
    secrets:
      - pg-credentials
    networks: 
      - front-network
      - back-network
    depends_on:
      - pgdb

  backend:
    build: ./backend
    ports:
      - "${BACKEND_PORT:-7000}:5000"
    networks:
      - back-network
    secrets:
      - pg-credentials
    depends_on:
      - pgdb


  pgdb:
    image: postgres
    networks:
      - back-network
    environment:
      - POSTGRES_DB=${DB:-sest}
      - POSTGRES_USER=${DB_USER:-postgres}
      - POSTGRES_PASSWORD=${DB_PASS:-password}


secrets:
  pg-credentials:
    file: .env


networks:
  front-network: {}
  
  back-network: {}